{"name": "test_login_invalid", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to be visible\nActual value: <element(s) not found> \nCall log:\n  - Expect \"to_be_visible\" with timeout 5000ms\n  - waiting for get_by_text(\"Invalid credentials\")", "trace": "page = <Page url='https://hocvancokimngan.com/login/'>, test_users = {'editor': {'email': 'test1111@gmail.com', 'password': '123456'}, 'viewer': {'email': 'viewer@example.com', 'password': 'P@ssw0rd'}}\n\n    @pytest.mark.ui\n    @pytest.mark.auth\n    @pytest.mark.regression\n    @allure.feature(\"Auth\")\n    @allure.story(\"Login\")\n    def test_login_invalid(page, test_users):\n        AuthPage(page).goto_login().login(\n            test_users[\"editor\"][\"email\"],\"wrong-password\")\n        # tuỳ UI\n>       AuthPage(page).toast_should_appear(\"Invalid credentials\")\n\ntests\\auth\\test_login_invalid.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.auth_page.AuthPage object at 0x0000027C996D77A0>, text = 'Invalid credentials'\n\n    def toast_should_appear(self, text: str):\n>       expect(self.page.get_by_text(text)).to_be_visible()\nE       AssertionError: Locator expected to be visible\nE       Actual value: <element(s) not found> \nE       Call log:\nE         - Expect \"to_be_visible\" with timeout 5000ms\nE         - waiting for get_by_text(\"Invalid credentials\")\n\npages\\base_page.py:24: AssertionError"}, "steps": [{"name": "Goto Login", "status": "passed", "start": 1756046158716, "stop": 1756046159683}, {"name": "Nhập thông tin đăng nhập", "status": "passed", "start": 1756046159683, "stop": 1756046159815}, {"name": "Đăng nhập", "status": "passed", "start": 1756046159815, "stop": 1756046161317}], "start": 1756046158716, "stop": 1756046166323, "uuid": "9a8f6c0a-c25c-4bca-9747-1d028cff0ad5", "historyId": "8922c08b01fb6010d52effa16df6e3dd", "testCaseId": "8922c08b01fb6010d52effa16df6e3dd", "fullName": "tests.auth.test_login_invalid#test_login_invalid", "labels": [{"name": "feature", "value": "Auth"}, {"name": "story", "value": "Login"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "auth"}, {"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_login_invalid"}, {"name": "host", "value": "Thanh-PC"}, {"name": "thread", "value": "22844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_login_invalid"}]}