{"name": "test_login_invalid", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 10000ms exceeded.\nCall log:\n  - navigating to \"https://hocvancokimngan.com/\", waiting until \"domcontentloaded\"", "trace": "page = <Page url='https://hocvancokimngan.com/'>, test_users = {'editor': {'email': 'test1111@gmail.com', 'password': '123456'}, 'viewer': {'email': 'viewer@example.com', 'password': 'P@ssw0rd'}}\n\n    @pytest.mark.ui\n    @pytest.mark.smoke\n    @pytest.mark.auth\n    @pytest.mark.regression\n    @allure.feature(\"Auth\")\n    @allure.story(\"Login\")\n    \n    \n    @allure.story(\"Login không thành công\")\n    def test_login_invalid(page, test_users):\n    \n        lg = AuthPage(page)\n>       lg.goto_login().login(test_users[\"editor\"][\"email\"], \"wrong-password\")\n\ntests\\auth\\test_login_invalid.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\auth_page.py:19: in goto_login\n    self.open()\npages\\base_page.py:40: in open\n    self.page.goto(url, wait_until=wait_until)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9019: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:556: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:153: in goto\n    await self._channel.send(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:69: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x0000025031D5BB30>, cb = <function Channel.send.<locals>.<lambda> at 0x00000250322DF740>, is_internal = False, title = None\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(\n            task, \"__pw_stack__\", None\n        ) or inspect.stack(0)\n    \n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 10000ms exceeded.\nE           Call log:\nE             - navigating to \"https://hocvancokimngan.com/\", waiting until \"domcontentloaded\"\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:558: TimeoutError"}, "steps": [{"name": "Goto Login", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 10000ms exceeded.\nCall log:\n  - navigating to \"https://hocvancokimngan.com/\", waiting until \"domcontentloaded\"\n\n", "trace": "  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\pages\\auth_page.py\", line 19, in goto_login\n    self.open()\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\pages\\base_page.py\", line 40, in open\n    self.page.goto(url, wait_until=wait_until)\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9019, in goto\n    self._sync(\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 556, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 153, in goto\n    await self._channel.send(\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 69, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\thanh\\PycharmProjects\\demo_pytest_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 558, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1756173256120, "stop": 1756173266137}], "start": 1756173256120, "stop": 1756173266137, "uuid": "832b0d11-e0c9-40c5-a008-966be2a803cd", "historyId": "8922c08b01fb6010d52effa16df6e3dd", "testCaseId": "8922c08b01fb6010d52effa16df6e3dd", "fullName": "tests.auth.test_login_invalid#test_login_invalid", "labels": [{"name": "story", "value": "Login"}, {"name": "story", "value": "Login không thành công"}, {"name": "feature", "value": "Auth"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "auth"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_login_invalid"}, {"name": "host", "value": "Thanh-PC"}, {"name": "thread", "value": "24688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_login_invalid"}]}